Sudoku: [[0, 3, 6, 8, 9, 2, 7, 1, 5],
        [5, 0, 2, 0, 7, 1, 9, 0, 3],
        [9, 0, 7, 5, 6, 3, 4, 8, 2],
        [0, 4, 3, 1, 5, 8, 2, 0, 7],
        [8, 5, 9, 6, 0, 7, 1, 3, 0],
        [7, 2, 0, 9, 3, 4, 8, 5, 6],
        [0, 0, 0, 2, 8, 6, 5, 0, 1],
        [0, 0, 0, 3, 1, 0, 0, 4, 9],
        [0, 0, 0, 7, 4, 9, 3, 2, 8]]